#!/bin/bash
sequence=1
timestamp=123456789

function createPayload() {
    payload="[{ \"sequence\": \"$1\", \"timestamp\": \"$2\", \"name\": \"$3\" }]"
}

function makeRequest() {
    curl -H "Content-Type: application/json" \
         -d "$1" \
         http://localhost:8080/v1/data
}

createPayload $sequence, $timestamp, "Data Load Start"
makeRequest "$payload"
timestamp=$((timestamp + 20))
createPayload $sequence, $timestamp, "XHR 1"
makeRequest "$payload"
timestamp=$((timestamp + 100))
createPayload $sequence, $timestamp, "XHR 2"
makeRequest "$payload"
timestamp=$((timestamp + 30))
createPayload $sequence, $timestamp, "XHR 3"
makeRequest "$payload"
timestamp=$((timestamp + 750))
createPayload $sequence, $timestamp, "XHR 4"
makeRequest "$payload"
timestamp=$((timestamp + 2400))
createPayload $sequence, $timestamp, "Data Load Complete"
makeRequest "$payload"




